version: '3'
services:
  db:
    container_name: student_moodle_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=parola
  node:
    container_name: student_moodle
    build: .
    ports:
      - 8080:8080
    tty: true
    links:
        - db
        - mongo
    environment:
      - MYSQL_URI=mysql://root:parola@db:3306/moodle
      - MONGO_URI=mongodb://mongo:27017/uploads
      - PORT=8080
  mongo:
    container_name: labs_storage
    image: mongo:3.0
    ports:
      - 27017:27017
    command: --smallfiles
